-- Drop Triggers
DROP TRIGGER IF EXISTS trg_generate_purchase_id ON "PurchaseDetails";
DROP TRIGGER IF EXISTS trg_generate_sales_id ON "SalesDetails";

-- Drop Functions
DROP FUNCTION IF EXISTS generate_purchase_id() CASCADE;
DROP FUNCTION IF EXISTS generate_sales_id() CASCADE;
DROP FUNCTION IF EXISTS get_expiry_date(INT) CASCADE;
DROP FUNCTION IF EXISTS get_user_details_by_email_id(
    pEmailID CHARACTER VARYING
);
DROP FUNCTION IF EXISTS insert_purchase_details(INT, DECIMAL, INT, INT, INT, INT) CASCADE;
DROP FUNCTION IF EXISTS insert_user_role(CHARACTER VARYING) CASCADE;
DROP FUNCTION IF EXISTS insert_item_details(CHARACTER VARYING, CHARACTER VARYING) CASCADE;
DROP FUNCTION IF EXISTS insert_user_details(CHARACTER VARYING, CHARACTER VARYING, INT, CHARACTER VARYING,
                                            CHARACTER VARYING, INT, CHARACTER VARYING) CASCADE;
DROP FUNCTION IF EXISTS insert_location_details(CHARACTER VARYING) CASCADE;

-- Drop Sequences
DROP SEQUENCE IF EXISTS purchase_id_seq CASCADE;
DROP SEQUENCE IF EXISTS sales_id_seq CASCADE;

-- Drop Tables
DROP TABLE IF EXISTS "SalesDetails" CASCADE;
DROP TABLE IF EXISTS "PurchaseDetails" CASCADE;
DROP TABLE IF EXISTS "UserDetails" CASCADE;
DROP TABLE IF EXISTS "UserRole" CASCADE;
DROP TABLE IF EXISTS "ItemsDetails" CASCADE;
DROP TABLE IF EXISTS "LocationDetails" CASCADE;
